# Generated by Django 3.1 on 2020-09-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_pessoa_depto_chefia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='depto_chefia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='chefia_depto', to='aplicacao.departamento'),
        ),
    ]
