# Generated by Django 3.1 on 2020-09-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_remove_tipopagamento_sigla'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoPagamento',
            new_name='TipoOperacao',
        ),
    ]
