# Generated by Django 3.1 on 2020-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0016_auto_20200924_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaofinanceiraentrada',
            name='situacao',
            field=models.CharField(choices=[(1, 'Recebido'), ('2', 'A Receber')], default='1', max_length=2),
        ),
    ]
