# Generated by Django 3.1 on 2020-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0017_auto_20200925_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaofinanceiraentrada',
            name='situacao',
            field=models.CharField(choices=[(1, 'Recebido'), (2, 'A Receber')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='operacaofinanceirasaida',
            name='situacao',
            field=models.CharField(choices=[(1, 'Pago'), (2, 'A Pagar')], default='1', max_length=2),
        ),
    ]
